### ISSUE TITLE
shouldn't go get line be different?

### ISSUE THREAD

**Issue by nhooyr** [bwmarrin/dca#18]
The go get line in the readme is 

```
go get github.com/bwmarrin/dca
```

Shouldn't it be

```
go get github.com/bwmarrin/dca/cmd/dca
```

**Comment by nhooyr** [comment]
The README.md for this folder: https://github.com/bwmarrin/dca/tree/master/cmd/dca

**Comment by bwmarrin** [comment]
Thanks.  This project probably needs a tremendous about of love at this point :(

Currently I wouldn't recommend using it and instead point you at the other implementations on the README.
